<?php

namespace Database\Seeders;

use App\Models\Pokemon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class PokemonGen1Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pokemons = [
            ["id" => 1, "name"=>"bulbasaur", "generation" => 1],
            ["id" => 2, "name"=>"ivysaur", "generation" => 1],
            ["id" => 3, "name"=>"venusaur", "generation" => 1],
            ["id" => 4, "name"=>"charmander", "generation" => 1],
            ["id" => 5, "name"=>"charmeleon", "generation" => 1],
            ["id" => 6, "name"=>"charizard", "generation" => 1],
            ["id" => 7, "name"=>"squirtle", "generation" => 1],
            ["id" => 8, "name"=>"wartortle", "generation" => 1],
            ["id" => 9, "name"=>"blastoise", "generation" => 1],
            ["id" => 10, "name"=>"caterpie", "generation" => 1],
            ["id" => 11, "name"=>"metapod", "generation" => 1],
            ["id" => 12, "name"=>"butterfree", "generation" => 1],
            ["id" => 13, "name"=>"weedle", "generation" => 1],
            ["id" => 14, "name"=>"kakuna", "generation" => 1],
            ["id" => 15, "name"=>"beedrill", "generation" => 1],
            ["id" => 16, "name"=>"pidgey", "generation" => 1],
            ["id" => 17, "name"=>"pidgeotto", "generation" => 1],
            ["id" => 18, "name"=>"pidgeot", "generation" => 1],
            ["id" => 19, "name"=>"rattata", "generation" => 1],
            ["id" => 20, "name"=>"raticate", "generation" => 1],
            ["id" => 21, "name"=>"spearow", "generation" => 1],
            ["id" => 22, "name"=>"fearow", "generation" => 1],
            ["id" => 23, "name"=>"ekans", "generation" => 1],
            ["id" => 24, "name"=>"arbok", "generation" => 1],
            ["id" => 25, "name"=>"pikachu", "generation" => 1],
            ["id" => 26, "name"=>"raichu", "generation" => 1],
            ["id" => 27, "name"=>"sandshrew", "generation" => 1],
            ["id" => 28, "name"=>"sandslash", "generation" => 1],
            ["id" => 29, "name"=>"nidoran-f", "generation" => 1],
            ["id" => 30, "name"=>"nidorina", "generation" => 1],
            ["id" => 31, "name"=>"nidoqueen", "generation" => 1],
            ["id" => 32, "name"=>"nidoran-m", "generation" => 1],
            ["id" => 33, "name"=>"nidorino", "generation" => 1],
            ["id" => 34, "name"=>"nidoking", "generation" => 1],
            ["id" => 35, "name"=>"clefairy", "generation" => 1],
            ["id" => 36, "name"=>"clefable", "generation" => 1],
            ["id" => 37, "name"=>"vulpix", "generation" => 1],
            ["id" => 38, "name"=>"ninetales", "generation" => 1],
            ["id" => 39, "name"=>"jigglypuff", "generation" => 1],
            ["id" => 40, "name"=>"wigglytuff", "generation" => 1],
            ["id" => 41, "name"=>"zubat", "generation" => 1],
            ["id" => 42, "name"=>"golbat", "generation" => 1],
            ["id" => 43, "name"=>"oddish", "generation" => 1],
            ["id" => 44, "name"=>"gloom", "generation" => 1],
            ["id" => 45, "name"=>"vileplume", "generation" => 1],
            ["id" => 46, "name"=>"paras", "generation" => 1],
            ["id" => 47, "name"=>"parasect", "generation" => 1],
            ["id" => 48, "name"=>"venonat", "generation" => 1],
            ["id" => 49, "name"=>"venomoth", "generation" => 1],
            ["id" => 50, "name"=>"diglett", "generation" => 1],
            ["id" => 51, "name"=>"dugtrio", "generation" => 1],
            ["id" => 52, "name"=>"meowth", "generation" => 1],
            ["id" => 53, "name"=>"persian", "generation" => 1],
            ["id" => 54, "name"=>"psyduck", "generation" => 1],
            ["id" => 55, "name"=>"golduck", "generation" => 1],
            ["id" => 56, "name"=>"mankey", "generation" => 1],
            ["id" => 57, "name"=>"primeape", "generation" => 1],
            ["id" => 58, "name"=>"growlithe", "generation" => 1],
            ["id" => 59, "name"=>"arcanine", "generation" => 1],
            ["id" => 60, "name"=>"poliwag", "generation" => 1],
            ["id" => 61, "name"=>"poliwhirl", "generation" => 1],
            ["id" => 62, "name"=>"poliwrath", "generation" => 1],
            ["id" => 63, "name"=>"abra", "generation" => 1],
            ["id" => 64, "name"=>"kadabra", "generation" => 1],
            ["id" => 65, "name"=>"alakazam", "generation" => 1],
            ["id" => 66, "name"=>"machop", "generation" => 1],
            ["id" => 67, "name"=>"machoke", "generation" => 1],
            ["id" => 68, "name"=>"machamp", "generation" => 1],
            ["id" => 69, "name"=>"bellsprout", "generation" => 1],
            ["id" => 70, "name"=>"weepinbell", "generation" => 1],
            ["id" => 71, "name"=>"victreebel", "generation" => 1],
            ["id" => 72, "name"=>"tentacool", "generation" => 1],
            ["id" => 73, "name"=>"tentacruel", "generation" => 1],
            ["id" => 74, "name"=>"geodude", "generation" => 1],
            ["id" => 75, "name"=>"graveler", "generation" => 1],
            ["id" => 76, "name"=>"golem", "generation" => 1],
            ["id" => 77, "name"=>"ponyta", "generation" => 1],
            ["id" => 78, "name"=>"rapidash", "generation" => 1],
            ["id" => 79, "name"=>"slowpoke", "generation" => 1],
            ["id" => 80, "name"=>"slowbro", "generation" => 1],
            ["id" => 81, "name"=>"magnemite", "generation" => 1],
            ["id" => 82, "name"=>"magneton", "generation" => 1],
            ["id" => 83, "name"=>"farfetchd", "generation" => 1],
            ["id" => 84, "name"=>"doduo", "generation" => 1],
            ["id" => 85, "name"=>"dodrio", "generation" => 1],
            ["id" => 86, "name"=>"seel", "generation" => 1],
            ["id" => 87, "name"=>"dewgong", "generation" => 1],
            ["id" => 88, "name"=>"grimer", "generation" => 1],
            ["id" => 89, "name"=>"muk", "generation" => 1],
            ["id" => 90, "name"=>"shellder", "generation" => 1],
            ["id" => 91, "name"=>"cloyster", "generation" => 1],
            ["id" => 92, "name"=>"gastly", "generation" => 1],
            ["id" => 93, "name"=>"haunter", "generation" => 1],
            ["id" => 94, "name"=>"gengar", "generation" => 1],
            ["id" => 95, "name"=>"onix", "generation" => 1],
            ["id" => 96, "name"=>"drowzee", "generation" => 1],
            ["id" => 97, "name"=>"hypno", "generation" => 1],
            ["id" => 98, "name"=>"krabby", "generation" => 1],
            ["id" => 99, "name"=>"kingler", "generation" => 1],
            ["id" => 100, "name"=>"voltorb", "generation" => 1],
            ["id" => 101, "name"=>"electrode", "generation" => 1],
            ["id" => 102, "name"=>"exeggcute", "generation" => 1],
            ["id" => 103, "name"=>"exeggutor", "generation" => 1],
            ["id" => 104, "name"=>"cubone", "generation" => 1],
            ["id" => 105, "name"=>"marowak", "generation" => 1],
            ["id" => 106, "name"=>"hitmonlee", "generation" => 1],
            ["id" => 107, "name"=>"hitmonchan", "generation" => 1],
            ["id" => 108, "name"=>"lickitung", "generation" => 1],
            ["id" => 109, "name"=>"koffing", "generation" => 1],
            ["id" => 110, "name"=>"weezing", "generation" => 1],
            ["id" => 111, "name"=>"rhyhorn", "generation" => 1],
            ["id" => 112, "name"=>"rhydon", "generation" => 1],
            ["id" => 113, "name"=>"chansey", "generation" => 1],
            ["id" => 114, "name"=>"tangela", "generation" => 1],
            ["id" => 115, "name"=>"kangaskhan", "generation" => 1],
            ["id" => 116, "name"=>"horsea", "generation" => 1],
            ["id" => 117, "name"=>"seadra", "generation" => 1],
            ["id" => 118, "name"=>"goldeen", "generation" => 1],
            ["id" => 119, "name"=>"seaking", "generation" => 1],
            ["id" => 120, "name"=>"staryu", "generation" => 1],
            ["id" => 121, "name"=>"starmie", "generation" => 1],
            ["id" => 122, "name"=>"mr. mime", "generation" => 1],
            ["id" => 123, "name"=>"scyther", "generation" => 1],
            ["id" => 124, "name"=>"jynx", "generation" => 1],
            ["id" => 125, "name"=>"electabuzz", "generation" => 1],
            ["id" => 126, "name"=>"magmar", "generation" => 1],
            ["id" => 127, "name"=>"pinsir", "generation" => 1],
            ["id" => 128, "name"=>"tauros", "generation" => 1],
            ["id" => 129, "name"=>"magikarp", "generation" => 1],
            ["id" => 130, "name"=>"gyarados", "generation" => 1],
            ["id" => 131, "name"=>"lapras", "generation" => 1],
            ["id" => 132, "name"=>"ditto", "generation" => 1],
            ["id" => 133, "name"=>"eevee", "generation" => 1],
            ["id" => 134, "name"=>"vaporeon", "generation" => 1],
            ["id" => 135, "name"=>"jolteon", "generation" => 1],
            ["id" => 136, "name"=>"flareon", "generation" => 1],
            ["id" => 137, "name"=>"porygon", "generation" => 1],
            ["id" => 138, "name"=>"omanyte", "generation" => 1],
            ["id" => 139, "name"=>"omastar", "generation" => 1],
            ["id" => 140, "name"=>"kabuto", "generation" => 1],
            ["id" => 141, "name"=>"kabutops", "generation" => 1],
            ["id" => 142, "name"=>"aerodactyl", "generation" => 1],
            ["id" => 143, "name"=>"snorlax", "generation" => 1],
            ["id" => 144, "name"=>"articuno", "generation" => 1],
            ["id" => 145, "name"=>"zapdos", "generation" => 1],
            ["id" => 146, "name"=>"moltres", "generation" => 1],
            ["id" => 147, "name"=>"dratini", "generation" => 1],
            ["id" => 148, "name"=>"dragonair", "generation" => 1],
            ["id" => 149, "name"=>"dragonite", "generation" => 1],
            ["id" => 150, "name"=>"mewtwo", "generation" => 1],
            ["id" => 151, "name"=>"mew", "generation" => 1],
        ];

        foreach ($pokemons as $pokemon) {
            Pokemon::create($pokemon);
        }
    }
}
